CC=gcc
CFLAGS=-g

build: client server client_udp server_udp client_lf server_lf

client: client.o

server: server.o

client_udp: client_udp.o

server_udp: server_udp.o

client_lf: client_lf.o

server_lf: server_lf.o

client.o: client.c

server.o: server.c

client_udp.o: client_udp.c

server_udp.o: server_udp.c

client_lf.o: client_lf.c

server_lf.o: server_lf.c
