CC=gcc
CFLAGS=-g

build: client server client_lf server_lf

client: client.o

server: server.o

client_lf: client_lf.o

server_lf: server_lf.o

client.o: client.c

server.o: server.c

client_lf.o: client_lf.c

server_lf.o: server_lf.c
